import { Archive, Cloud, Heart } from "lucide-react";

// export const demoBookmarks: Bookmark[] = [
//   {
//     id: "1",
//     userId: "user1",
//     collectionId: "components",
//     url: "https://example.com",
//     name: "Example Website",
//     title: "Example Website",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "This is an example link.",
//     // tags: ["example", "website"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "example.com",
//     siteName: "Example",
//     author: "John Doe",
//     publishedAt: new Date("2023-01-01"),
//     createdAt: new Date("2023-01-01"),
//     updatedAt: new Date("2023-01-01"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "2",
//     userId: "user1",
//     collectionId: "react",
//     url: "https://another-example.com",
//     name: "Another Example",
//     title: "Another Example",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "This is another example link.",
//     isArchived: false,
//     isFavorite: false,
//     domain: "another-example.com",
//     siteName: "Another Example",
//     author: "Jane Smith",
//     publishedAt: new Date("2023-01-01"),
//     createdAt: new Date("2023-01-01"),
//     updatedAt: new Date("2023-01-01"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "3",
//     userId: "user1",
//     collectionId: "next-js",
//     url: "https://third-example.com",
//     name: "Third Example",
//     title: "Third Example",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "This is the third example link.",
//     // tags: ["third", "example"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "third-example.com",
//     siteName: "Third Example",
//     author: "Alice Johnson",
//     publishedAt: new Date("2023-01-01"),
//     createdAt: new Date("2023-01-01"),
//     updatedAt: new Date("2023-01-01"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "4",
//     userId: "user2",
//     collectionId: "javascript",
//     url: "https://site4.com",
//     name: "Site Four",
//     title: "Site Four",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site four.",
//     // tags: ["site", "four"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site4.com",
//     siteName: "Site Four",
//     author: "Bob Brown",
//     publishedAt: new Date("2023-02-01"),
//     createdAt: new Date("2023-02-01"),
//     updatedAt: new Date("2023-02-01"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "5",
//     userId: "user2",
//     collectionId: "typescript",
//     url: "https://site5.com",
//     name: "Site Five",
//     title: "Site Five",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site five.",
//     // tags: ["site", "five"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site5.com",
//     siteName: "Site Five",
//     author: "Carol White",
//     publishedAt: new Date("2023-02-02"),
//     createdAt: new Date("2023-02-02"),
//     updatedAt: new Date("2023-02-02"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "6",
//     userId: "user3",
//     collectionId: "tailwindcss",
//     url: "https://site6.com",
//     name: "Site Six",
//     title: "Site Six",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site six.",
//     // tags: ["site", "six"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site6.com",
//     siteName: "Site Six",
//     author: "David Green",
//     publishedAt: new Date("2023-02-03"),
//     createdAt: new Date("2023-02-03"),
//     updatedAt: new Date("2023-02-03"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "7",
//     userId: "user3",
//     collectionId: null,
//     url: "https://site7.com",
//     name: "Site Seven",
//     title: "Site Seven",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site seven.",
//     // tags: ["site", "seven"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site7.com",
//     siteName: "Site Seven",
//     author: "Eve Black",
//     publishedAt: new Date("2023-02-04"),
//     createdAt: new Date("2023-02-04"),
//     updatedAt: new Date("2023-02-04"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "8",
//     userId: "user4",
//     collectionId: null,
//     url: "https://site8.com",
//     name: "Site Eight",
//     title: "Site Eight",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site eight.",
//     // tags: ["site", "eight"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site8.com",
//     siteName: "Site Eight",
//     author: "Frank Blue",
//     publishedAt: new Date("2023-02-05"),
//     createdAt: new Date("2023-02-05"),
//     updatedAt: new Date("2023-02-05"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "9",
//     userId: "user4",
//     collectionId: null,
//     url: "https://site9.com",
//     name: "Site Nine",
//     title: "Site Nine",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site nine.",
//     // tags: ["site", "nine"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site9.com",
//     siteName: "Site Nine",
//     author: "Grace Red",
//     publishedAt: new Date("2023-02-06"),
//     createdAt: new Date("2023-02-06"),
//     updatedAt: new Date("2023-02-06"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "10",
//     userId: "user5",
//     collectionId: null,
//     url: "https://site10.com",
//     name: "Site Ten",
//     title: "Site Ten",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site ten.",
//     // tags: ["site", "ten"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site10.com",
//     siteName: "Site Ten",
//     author: "Hank Violet",
//     publishedAt: new Date("2023-02-07"),
//     createdAt: new Date("2023-02-07"),
//     updatedAt: new Date("2023-02-07"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "11",
//     userId: "user5",
//     collectionId: null,
//     url: "https://site11.com",
//     name: "Site Eleven",
//     title: "Site Eleven",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site eleven.",
//     // tags: ["site", "eleven"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site11.com",
//     siteName: "Site Eleven",
//     author: "Ivy Indigo",
//     publishedAt: new Date("2023-02-08"),
//     createdAt: new Date("2023-02-08"),
//     updatedAt: new Date("2023-02-08"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "12",
//     userId: "user6",
//     collectionId: null,
//     url: "https://site12.com",
//     name: "Site Twelve",
//     title: "Site Twelve",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twelve.",
//     // tags: ["site", "twelve"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site12.com",
//     siteName: "Site Twelve",
//     author: "Jack Orange",
//     publishedAt: new Date("2023-02-09"),
//     createdAt: new Date("2023-02-09"),
//     updatedAt: new Date("2023-02-09"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "13",
//     userId: "user6",
//     collectionId: null,
//     url: "https://site13.com",
//     name: "Site Thirteen",
//     title: "Site Thirteen",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirteen.",
//     // tags: ["site", "thirteen"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site13.com",
//     siteName: "Site Thirteen",
//     author: "Karen Pink",
//     publishedAt: new Date("2023-02-10"),
//     createdAt: new Date("2023-02-10"),
//     updatedAt: new Date("2023-02-10"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "14",
//     userId: "user7",
//     collectionId: null,
//     url: "https://site14.com",
//     name: "Site Fourteen",
//     title: "Site Fourteen",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site fourteen.",
//     // tags: ["site", "fourteen"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site14.com",
//     siteName: "Site Fourteen",
//     author: "Leo Silver",
//     publishedAt: new Date("2023-02-11"),
//     createdAt: new Date("2023-02-11"),
//     updatedAt: new Date("2023-02-11"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "15",
//     userId: "user7",
//     collectionId: null,
//     url: "https://site15.com",
//     name: "Site Fifteen",
//     title: "Site Fifteen",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site fifteen.",
//     // tags: ["site", "fifteen"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site15.com",
//     siteName: "Site Fifteen",
//     author: "Mona Gold",
//     publishedAt: new Date("2023-02-12"),
//     createdAt: new Date("2023-02-12"),
//     updatedAt: new Date("2023-02-12"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "16",
//     userId: "user8",
//     collectionId: null,
//     url: "https://site16.com",
//     name: "Site Sixteen",
//     title: "Site Sixteen",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site sixteen.",
//     // tags: ["site", "sixteen"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site16.com",
//     siteName: "Site Sixteen",
//     author: "Nina Bronze",
//     publishedAt: new Date("2023-02-13"),
//     createdAt: new Date("2023-02-13"),
//     updatedAt: new Date("2023-02-13"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "17",
//     userId: "user8",
//     collectionId: null,
//     url: "https://site17.com",
//     name: "Site Seventeen",
//     title: "Site Seventeen",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site seventeen.",
//     // tags: ["site", "seventeen"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site17.com",
//     siteName: "Site Seventeen",
//     author: "Oscar Copper",
//     publishedAt: new Date("2023-02-14"),
//     createdAt: new Date("2023-02-14"),
//     updatedAt: new Date("2023-02-14"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "18",
//     userId: "user9",
//     collectionId: null,
//     url: "https://site18.com",
//     name: "Site Eighteen",
//     title: "Site Eighteen",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site eighteen.",
//     // tags: ["site", "eighteen"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site18.com",
//     siteName: "Site Eighteen",
//     author: "Pauline Jade",
//     publishedAt: new Date("2023-02-15"),
//     createdAt: new Date("2023-02-15"),
//     updatedAt: new Date("2023-02-15"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "19",
//     userId: "user9",
//     collectionId: null,
//     url: "https://site19.com",
//     name: "Site Nineteen",
//     title: "Site Nineteen",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site nineteen.",
//     // tags: ["site", "nineteen"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site19.com",
//     siteName: "Site Nineteen",
//     author: "Quinn Lime",
//     publishedAt: new Date("2023-02-16"),
//     createdAt: new Date("2023-02-16"),
//     updatedAt: new Date("2023-02-16"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "20",
//     userId: "user10",
//     collectionId: null,
//     url: "https://site20.com",
//     name: "Site Twenty",
//     title: "Site Twenty",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty.",
//     // tags: ["site", "twenty"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site20.com",
//     siteName: "Site Twenty",
//     author: "Rita Mint",
//     publishedAt: new Date("2023-02-17"),
//     createdAt: new Date("2023-02-17"),
//     updatedAt: new Date("2023-02-17"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "21",
//     userId: "user10",
//     collectionId: null,
//     url: "https://site21.com",
//     name: "Site Twenty-One",
//     title: "Site Twenty-One",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty-one.",
//     // tags: ["site", "twenty-one"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site21.com",
//     siteName: "Site Twenty-One",
//     author: "Sam Navy",
//     publishedAt: new Date("2023-02-18"),
//     createdAt: new Date("2023-02-18"),
//     updatedAt: new Date("2023-02-18"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "22",
//     userId: "user11",
//     collectionId: null,
//     url: "https://site22.com",
//     name: "Site Twenty-Two",
//     title: "Site Twenty-Two",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty-two.",
//     // tags: ["site", "twenty-two"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site22.com",
//     siteName: "Site Twenty-Two",
//     author: "Tina Olive",
//     publishedAt: new Date("2023-02-19"),
//     createdAt: new Date("2023-02-19"),
//     updatedAt: new Date("2023-02-19"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "23",
//     userId: "user11",
//     collectionId: null,
//     url: "https://site23.com",
//     name: "Site Twenty-Three",
//     title: "Site Twenty-Three",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty-three.",
//     // tags: ["site", "twenty-three"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site23.com",
//     siteName: "Site Twenty-Three",
//     author: "Uma Peach",
//     publishedAt: new Date("2023-02-20"),
//     createdAt: new Date("2023-02-20"),
//     updatedAt: new Date("2023-02-20"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "24",
//     userId: "user12",
//     collectionId: null,
//     url: "https://site24.com",
//     name: "Site Twenty-Four",
//     title: "Site Twenty-Four",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty-four.",
//     // tags: ["site", "twenty-four"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site24.com",
//     siteName: "Site Twenty-Four",
//     author: "Vera Plum",
//     publishedAt: new Date("2023-02-21"),
//     createdAt: new Date("2023-02-21"),
//     updatedAt: new Date("2023-02-21"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "25",
//     userId: "user12",
//     collectionId: null,
//     url: "https://site25.com",
//     name: "Site Twenty-Five",
//     title: "Site Twenty-Five",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty-five.",
//     // tags: ["site", "twenty-five"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site25.com",
//     siteName: "Site Twenty-Five",
//     author: "Will Quartz",
//     publishedAt: new Date("2023-02-22"),
//     createdAt: new Date("2023-02-22"),
//     updatedAt: new Date("2023-02-22"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "26",
//     userId: "user13",
//     collectionId: null,
//     url: "https://site26.com",
//     name: "Site Twenty-Six",
//     title: "Site Twenty-Six",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty-six.",
//     // tags: ["site", "twenty-six"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site26.com",
//     siteName: "Site Twenty-Six",
//     author: "Xena Ruby",
//     publishedAt: new Date("2023-02-23"),
//     createdAt: new Date("2023-02-23"),
//     updatedAt: new Date("2023-02-23"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "27",
//     userId: "user13",
//     collectionId: null,
//     url: "https://site27.com",
//     name: "Site Twenty-Seven",
//     title: "Site Twenty-Seven",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty-seven.",
//     // tags: ["site", "twenty-seven"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site27.com",
//     siteName: "Site Twenty-Seven",
//     author: "Yara Sapphire",
//     publishedAt: new Date("2023-02-24"),
//     createdAt: new Date("2023-02-24"),
//     updatedAt: new Date("2023-02-24"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "28",
//     userId: "user14",
//     collectionId: null,
//     url: "https://site28.com",
//     name: "Site Twenty-Eight",
//     title: "Site Twenty-Eight",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty-eight.",
//     // tags: ["site", "twenty-eight"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site28.com",
//     siteName: "Site Twenty-Eight",
//     author: "Zane Topaz",
//     publishedAt: new Date("2023-02-25"),
//     createdAt: new Date("2023-02-25"),
//     updatedAt: new Date("2023-02-25"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "29",
//     userId: "user14",
//     collectionId: null,
//     url: "https://site29.com",
//     name: "Site Twenty-Nine",
//     title: "Site Twenty-Nine",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site twenty-nine.",
//     // tags: ["site", "twenty-nine"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site29.com",
//     siteName: "Site Twenty-Nine",
//     author: "Amy Amber",
//     publishedAt: new Date("2023-02-26"),
//     createdAt: new Date("2023-02-26"),
//     updatedAt: new Date("2023-02-26"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "30",
//     userId: "user15",
//     collectionId: null,
//     url: "https://site30.com",
//     name: "Site Thirty",
//     title: "Site Thirty",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty.",
//     // tags: ["site", "thirty"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site30.com",
//     siteName: "Site Thirty",
//     author: "Ben Brown",
//     publishedAt: new Date("2023-02-27"),
//     createdAt: new Date("2023-02-27"),
//     updatedAt: new Date("2023-02-27"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "31",
//     userId: "user15",
//     collectionId: null,
//     url: "https://site31.com",
//     name: "Site Thirty-One",
//     title: "Site Thirty-One",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty-one.",
//     // tags: ["site", "thirty-one"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site31.com",
//     siteName: "Site Thirty-One",
//     author: "Cara Cyan",
//     publishedAt: new Date("2023-02-28"),
//     createdAt: new Date("2023-02-28"),
//     updatedAt: new Date("2023-02-28"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "32",
//     userId: "user16",
//     collectionId: null,
//     url: "https://site32.com",
//     name: "Site Thirty-Two",
//     title: "Site Thirty-Two",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty-two.",
//     // tags: ["site", "thirty-two"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site32.com",
//     siteName: "Site Thirty-Two",
//     author: "Derek Emerald",
//     publishedAt: new Date("2023-03-01"),
//     createdAt: new Date("2023-03-01"),
//     updatedAt: new Date("2023-03-01"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "33",
//     userId: "user16",
//     collectionId: null,
//     url: "https://site33.com",
//     name: "Site Thirty-Three",
//     title: "Site Thirty-Three",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty-three.",
//     // tags: ["site", "thirty-three"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site33.com",
//     siteName: "Site Thirty-Three",
//     author: "Ella Fuchsia",
//     publishedAt: new Date("2023-03-02"),
//     createdAt: new Date("2023-03-02"),
//     updatedAt: new Date("2023-03-02"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "34",
//     userId: "user17",
//     collectionId: null,
//     url: "https://site34.com",
//     name: "Site Thirty-Four",
//     title: "Site Thirty-Four",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty-four.",
//     // tags: ["site", "thirty-four"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site34.com",
//     siteName: "Site Thirty-Four",
//     author: "Finn Gray",
//     publishedAt: new Date("2023-03-03"),
//     createdAt: new Date("2023-03-03"),
//     updatedAt: new Date("2023-03-03"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "35",
//     userId: "user17",
//     collectionId: null,
//     url: "https://site35.com",
//     name: "Site Thirty-Five",
//     title: "Site Thirty-Five",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty-five.",
//     // tags: ["site", "thirty-five"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site35.com",
//     siteName: "Site Thirty-Five",
//     author: "Gina Honey",
//     publishedAt: new Date("2023-03-04"),
//     createdAt: new Date("2023-03-04"),
//     updatedAt: new Date("2023-03-04"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "36",
//     userId: "user18",
//     collectionId: null,
//     url: "https://site36.com",
//     name: "Site Thirty-Six",
//     title: "Site Thirty-Six",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty-six.",
//     // tags: ["site", "thirty-six"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site36.com",
//     siteName: "Site Thirty-Six",
//     author: "Henry Ivory",
//     publishedAt: new Date("2023-03-05"),
//     createdAt: new Date("2023-03-05"),
//     updatedAt: new Date("2023-03-05"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "37",
//     userId: "user18",
//     collectionId: null,
//     url: "https://site37.com",
//     name: "Site Thirty-Seven",
//     title: "Site Thirty-Seven",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty-seven.",
//     // tags: ["site", "thirty-seven"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site37.com",
//     siteName: "Site Thirty-Seven",
//     author: "Isla Jade",
//     publishedAt: new Date("2023-03-06"),
//     createdAt: new Date("2023-03-06"),
//     updatedAt: new Date("2023-03-06"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "38",
//     userId: "user19",
//     collectionId: null,
//     url: "https://site38.com",
//     name: "Site Thirty-Eight",
//     title: "Site Thirty-Eight",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty-eight.",
//     // tags: ["site", "thirty-eight"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site38.com",
//     siteName: "Site Thirty-Eight",
//     author: "Jake Khaki",
//     publishedAt: new Date("2023-03-07"),
//     createdAt: new Date("2023-03-07"),
//     updatedAt: new Date("2023-03-07"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "39",
//     userId: "user19",
//     collectionId: null,
//     url: "https://site39.com",
//     name: "Site Thirty-Nine",
//     title: "Site Thirty-Nine",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site thirty-nine.",
//     // tags: ["site", "thirty-nine"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site39.com",
//     siteName: "Site Thirty-Nine",
//     author: "Kara Lemon",
//     publishedAt: new Date("2023-03-08"),
//     createdAt: new Date("2023-03-08"),
//     updatedAt: new Date("2023-03-08"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "40",
//     userId: "user20",
//     collectionId: null,
//     url: "https://site40.com",
//     name: "Site Forty",
//     title: "Site Forty",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty.",
//     // tags: ["site", "forty"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site40.com",
//     siteName: "Site Forty",
//     author: "Liam Magenta",
//     publishedAt: new Date("2023-03-09"),
//     createdAt: new Date("2023-03-09"),
//     updatedAt: new Date("2023-03-09"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "41",
//     userId: "user20",
//     collectionId: null,
//     url: "https://site41.com",
//     name: "Site Forty-One",
//     title: "Site Forty-One",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty-one.",
//     // tags: ["site", "forty-one"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site41.com",
//     siteName: "Site Forty-One",
//     author: "Mia Navy",
//     publishedAt: new Date("2023-03-10"),
//     createdAt: new Date("2023-03-10"),
//     updatedAt: new Date("2023-03-10"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "42",
//     userId: "user21",
//     collectionId: null,
//     url: "https://site42.com",
//     name: "Site Forty-Two",
//     title: "Site Forty-Two",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty-two.",
//     // tags: ["site", "forty-two"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site42.com",
//     siteName: "Site Forty-Two",
//     author: "Noah Olive",
//     publishedAt: new Date("2023-03-11"),
//     createdAt: new Date("2023-03-11"),
//     updatedAt: new Date("2023-03-11"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "43",
//     userId: "user21",
//     collectionId: null,
//     url: "https://site43.com",
//     name: "Site Forty-Three",
//     title: "Site Forty-Three",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty-three.",
//     // tags: ["site", "forty-three"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site43.com",
//     siteName: "Site Forty-Three",
//     author: "Olivia Pink",
//     publishedAt: new Date("2023-03-12"),
//     createdAt: new Date("2023-03-12"),
//     updatedAt: new Date("2023-03-12"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "44",
//     userId: "user22",
//     collectionId: null,
//     url: "https://site44.com",
//     name: "Site Forty-Four",
//     title: "Site Forty-Four",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty-four.",
//     // tags: ["site", "forty-four"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site44.com",
//     siteName: "Site Forty-Four",
//     author: "Peter Quartz",
//     publishedAt: new Date("2023-03-13"),
//     createdAt: new Date("2023-03-13"),
//     updatedAt: new Date("2023-03-13"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "45",
//     userId: "user22",
//     collectionId: null,
//     url: "https://site45.com",
//     name: "Site Forty-Five",
//     title: "Site Forty-Five",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty-five.",
//     // tags: ["site", "forty-five"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site45.com",
//     siteName: "Site Forty-Five",
//     author: "Quincy Ruby",
//     publishedAt: new Date("2023-03-14"),
//     createdAt: new Date("2023-03-14"),
//     updatedAt: new Date("2023-03-14"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "46",
//     userId: "user23",
//     collectionId: null,
//     url: "https://site46.com",
//     name: "Site Forty-Six",
//     title: "Site Forty-Six",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty-six.",
//     // tags: ["site", "forty-six"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site46.com",
//     siteName: "Site Forty-Six",
//     author: "Riley Sapphire",
//     publishedAt: new Date("2023-03-15"),
//     createdAt: new Date("2023-03-15"),
//     updatedAt: new Date("2023-03-15"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "47",
//     userId: "user23",
//     collectionId: null,
//     url: "https://site47.com",
//     name: "Site Forty-Seven",
//     title: "Site Forty-Seven",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty-seven.",
//     // tags: ["site", "forty-seven"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site47.com",
//     siteName: "Site Forty-Seven",
//     author: "Sophie Topaz",
//     publishedAt: new Date("2023-03-16"),
//     createdAt: new Date("2023-03-16"),
//     updatedAt: new Date("2023-03-16"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "48",
//     userId: "user24",
//     collectionId: null,
//     url: "https://site48.com",
//     name: "Site Forty-Eight",
//     title: "Site Forty-Eight",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty-eight.",
//     // tags: ["site", "forty-eight"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site48.com",
//     siteName: "Site Forty-Eight",
//     author: "Thomas Umber",
//     publishedAt: new Date("2023-03-17"),
//     createdAt: new Date("2023-03-17"),
//     updatedAt: new Date("2023-03-17"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "49",
//     userId: "user24",
//     collectionId: null,
//     url: "https://site49.com",
//     name: "Site Forty-Nine",
//     title: "Site Forty-Nine",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site forty-nine.",
//     // tags: ["site", "forty-nine"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site49.com",
//     siteName: "Site Forty-Nine",
//     author: "Uma Violet",
//     publishedAt: new Date("2023-03-18"),
//     createdAt: new Date("2023-03-18"),
//     updatedAt: new Date("2023-03-18"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "50",
//     userId: "user25",
//     collectionId: null,
//     url: "https://site50.com",
//     name: "Site Fifty",
//     title: "Site Fifty",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site fifty.",
//     // tags: ["site", "fifty"],
//     isArchived: false,
//     isFavorite: false,
//     domain: "site50.com",
//     siteName: "Site Fifty",
//     author: "Victor White",
//     publishedAt: new Date("2023-03-19"),
//     createdAt: new Date("2023-03-19"),
//     updatedAt: new Date("2023-03-19"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "51",
//     userId: "user25",
//     collectionId: null,
//     url: "https://site51.com",
//     name: "Site Fifty-One",
//     title: "Site Fifty-One",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site fifty-one.",
//     // tags: ["site", "fifty-one"],
//     isArchived: true,
//     isFavorite: false,
//     domain: "site51.com",
//     siteName: "Site Fifty-One",
//     author: "Wendy Xanthic",
//     publishedAt: new Date("2023-03-20"),
//     createdAt: new Date("2023-03-20"),
//     updatedAt: new Date("2023-03-20"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   },
//   {
//     id: "52",
//     userId: "user26",
//     collectionId: null,
//     url: "https://site52.com",
//     name: "Site Fifty-Two",
//     title: "Site Fifty-Two",
//     imageURL: null,
//     type: null,
//     locale: null,
//     description: "Description for site fifty-two.",
//     // tags: ["site", "fifty-two"],
//     isArchived: false,
//     isFavorite: true,
//     domain: "site52.com",
//     siteName: "Site Fifty-Two",
//     author: "Xavier Yellow",
//     publishedAt: new Date("2023-03-21"),
//     createdAt: new Date("2023-03-21"),
//     updatedAt: new Date("2023-03-21"),
//     readingProgress: null,
//     readAt: null,
//     canonicalUrl: null,
//     excerpt: null,
//     content: null,
//     contentHtml: null,
//     featuredImageUrl: null,
//     readingTimeMinutes: null,
//     wordCount: null,
//     images: null
//   }
// ];

export const sidebarData = {
  main: [
    {
      name: "All",
      count: "2109",
      icon: Cloud,
      slug: "all"
    },
    {
      name: "Favorites",
      count: "109",
      icon: Heart,
      slug: "all?favorite=true"
    },
    {
      name: "Archived",
      count: "200",
      icon: Archive,
      slug: "all?archived=true"
    }
  ],
  collections: [
    // {
    //   slug: "a-really-really-long-collection-name",
    //   name: "A really really long collection name",
    //   nested: [{ name: "A nested folder", slug: "a-nested-folder" }]
    // },
    // {
    //   slug: "short-name",
    //   name: "Short name",
    //   nested: [
    //     {
    //       name: "nested folder",
    //       slug: "nested-folder",
    //       nested: [{ name: "deeply nested", slug: "deeply-nested" }]
    //     }
    //   ]
    // },
    { count: 1, slug: "components", name: "components", nested: [] },
    { count: 1, slug: "react", name: "React", nested: [] },
    { count: 1, slug: "next-js", name: "Next.js", nested: [] },
    { count: 1, slug: "javascript", name: "JavaScript", nested: [] },
    { count: 1, slug: "typescript", name: "TypeScript", nested: [] },
    { count: 1, slug: "tailwindcss", name: "TailwindCSS", nested: [] },
    { count: 0, slug: "node-js", name: "Node.js", nested: [] },
    { count: 0, slug: "express", name: "Express", nested: [] },
    { count: 0, slug: "mongodb", name: "MongoDB", nested: [] },
    { count: 0, slug: "prisma", name: "Prisma", nested: [] },
    { count: 0, slug: "docker", name: "Docker", nested: [] },
    { count: 0, slug: "kubernetes", name: "Kubernetes", nested: [] },
    { count: 0, slug: "aws", name: "AWS", nested: [] }
  ]
};
